START TRANSACTION;
Lock tables event write;


-- Malfuncionamiento del dispositivo
SET @max = (SELECT count(*) FROM event where patient_id=21);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,malfunction_device_type_id,urgent_surgery_id,change_assistance_components) VALUES (21,0,0,'espamacs.event.MalfunctionDevice',@max,'2014-10-15 00:00:00',354,0,360,375,1);
SET @max = (SELECT count(*) FROM event where patient_id=21);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,malfunction_device_type_id,urgent_surgery_id,change_assistance_components) VALUES (21,0,0,'espamacs.event.MalfunctionDevice',@max,'2014-11-18 00:00:00',354,0,361,375,1);
SET @max = (SELECT count(*) FROM event where patient_id=20);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,malfunction_device_type_id,urgent_surgery_id,change_assistance_components) VALUES (20,0,0,'espamacs.event.MalfunctionDevice',@max,'2014-09-05 00:00:00',352,0,362,374,1);
SET @max = (SELECT count(*) FROM event where patient_id=26);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,malfunction_device_type_id,urgent_surgery_id,change_assistance_components) VALUES (26,0,0,'espamacs.event.MalfunctionDevice',@max,'2013-02-01 00:00:00',351,0,364,373,1);
SET @max = (SELECT count(*) FROM event where patient_id=78);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,malfunction_device_type_id,urgent_surgery_id,change_assistance_components) VALUES (78,0,0,'espamacs.event.MalfunctionDevice',@max,'2015-02-16 00:00:00',354,0,359,375,1);
SET @max = (SELECT count(*) FROM event where patient_id=122);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,malfunction_device_type_id,urgent_surgery_id,change_assistance_components) VALUES (122,0,0,'espamacs.event.MalfunctionDevice',@max,'2014-02-14 00:00:00',351,0,364,373,0);
SET @max = (SELECT count(*) FROM event where patient_id=150);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,malfunction_device_type_id,urgent_surgery_id,change_assistance_components) VALUES (150,0,0,'espamacs.event.MalfunctionDevice',@max,'2015-04-14 00:00:00',354,0,361,375,1);
SET @max = (SELECT count(*) FROM event where patient_id=179);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,malfunction_device_type_id,urgent_surgery_id,change_assistance_components) VALUES (179,0,0,'espamacs.event.MalfunctionDevice',@max,'2012-07-31 00:00:00',351,1,364,373,0);
SET @max = (SELECT count(*) FROM event where patient_id=193);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,malfunction_device_type_id,urgent_surgery_id,change_assistance_components) VALUES (193,0,0,'espamacs.event.MalfunctionDevice',@max,'2015-04-10 00:00:00',351,0,363,373,0);
SET @max = (SELECT count(*) FROM event where patient_id=151);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,malfunction_device_type_id,urgent_surgery_id,change_assistance_components) VALUES (151,0,0,'espamacs.event.MalfunctionDevice',@max,'2015-08-12 00:00:00',354,0,362,375,0);
SET @max = (SELECT count(*) FROM event where patient_id=185);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,malfunction_device_type_id,urgent_surgery_id,change_assistance_components) VALUES (185,0,0,'espamacs.event.MalfunctionDevice',@max,'2014-01-22 00:00:00',351,0,363,375,1);
SET @max = (SELECT count(*) FROM event where patient_id=233);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,malfunction_device_type_id,urgent_surgery_id,change_assistance_components) VALUES (233,0,0,'espamacs.event.MalfunctionDevice',@max,'2014-04-22 00:00:00',351,1,363,373,1);
SET @max = (SELECT count(*) FROM event where patient_id=204);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,malfunction_device_type_id,urgent_surgery_id,change_assistance_components) VALUES (204,0,0,'espamacs.event.MalfunctionDevice',@max,'2015-03-23 00:00:00',351,0,362,373,1);
SET @max = (SELECT count(*) FROM event where patient_id=289);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,malfunction_device_type_id,urgent_surgery_id,change_assistance_components) VALUES (289,0,0,'espamacs.event.MalfunctionDevice',@max,'2015-09-18 00:00:00',351,0,363,373,1);
SET @max = (SELECT count(*) FROM event where patient_id=78);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,malfunction_device_type_id,urgent_surgery_id,change_assistance_components) VALUES (78,0,0,'espamacs.event.MalfunctionDevice',@max,'2014-12-23 00:00:00',354,0,360,375,1);
SET @max = (SELECT count(*) FROM event where patient_id=78);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,malfunction_device_type_id,urgent_surgery_id,change_assistance_components) VALUES (78,0,0,'espamacs.event.MalfunctionDevice',@max,'2015-03-18 00:00:00',354,0,365,375,1);
SET @max = (SELECT count(*) FROM event where patient_id=197);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,malfunction_device_type_id,urgent_surgery_id,change_assistance_components) VALUES (197,0,0,'espamacs.event.MalfunctionDevice',@max,'2015-07-15 00:00:00',352,0,359,375,1);
SET @max = (SELECT count(*) FROM event where patient_id=197);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,malfunction_device_type_id,urgent_surgery_id,change_assistance_components) VALUES (197,0,0,'espamacs.event.MalfunctionDevice',@max,'2015-08-17 00:00:00',352,0,360,375,1);
SET @max = (SELECT count(*) FROM event where patient_id=199);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,malfunction_device_type_id,urgent_surgery_id,change_assistance_components) VALUES (199,0,0,'espamacs.event.MalfunctionDevice',@max,'2015-05-26 00:00:00',354,0,362,375,1);
SET @max = (SELECT count(*) FROM event where patient_id=327);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,malfunction_device_type_id,urgent_surgery_id,change_assistance_components) VALUES (327,0,0,'espamacs.event.MalfunctionDevice',@max,'2016-02-14 00:00:00',351,1,362,375,1);
SET @max = (SELECT count(*) FROM event where patient_id=33);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,malfunction_device_type_id,urgent_surgery_id,change_assistance_components) VALUES (33,0,0,'espamacs.event.MalfunctionDevice',@max,'2013-03-28 00:00:00',351,1,359,373,0);


-- Hemorragias
SET @max = (SELECT count(*) FROM event where patient_id=56);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,hemorrhage_cause_id,hemorrhage_treatment_id) VALUES (56,0,0,'espamacs.event.Hemorrhage',@max,'2014-09-23 00:00:00',351,1,369,376);
SET @max = (SELECT count(*) FROM event where patient_id=63);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,hemorrhage_cause_id,hemorrhage_treatment_id) VALUES (63,0,0,'espamacs.event.Hemorrhage',@max,'2014-02-12 00:00:00',351,1,370,376);
SET @max = (SELECT count(*) FROM event where patient_id=104);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,hemorrhage_cause_id,hemorrhage_treatment_id) VALUES (104,0,0,'espamacs.event.Hemorrhage',@max,'2014-02-07 00:00:00',351,1,371,377);
SET @max = (SELECT count(*) FROM event where patient_id=180);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,hemorrhage_cause_id,hemorrhage_treatment_id) VALUES (180,0,0,'espamacs.event.Hemorrhage',@max,'2012-11-19 00:00:00',351,0,369,376);
SET @max = (SELECT count(*) FROM event where patient_id=183);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,hemorrhage_cause_id,hemorrhage_treatment_id) VALUES (183,0,0,'espamacs.event.Hemorrhage',@max,'2015-05-05 00:00:00',351,0,369,377);
SET @max = (SELECT count(*) FROM event where patient_id=196);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,hemorrhage_cause_id,hemorrhage_treatment_id) VALUES (196,0,0,'espamacs.event.Hemorrhage',@max,'2015-02-26 00:00:00',351,1,372,378);
SET @max = (SELECT count(*) FROM event where patient_id=205);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,hemorrhage_cause_id,hemorrhage_treatment_id) VALUES (205,0,0,'espamacs.event.Hemorrhage',@max,'2015-02-23 00:00:00',351,1,369,376);
SET @max = (SELECT count(*) FROM event where patient_id=207);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,hemorrhage_cause_id,hemorrhage_treatment_id) VALUES (207,0,0,'espamacs.event.Hemorrhage',@max,'2014-04-22 00:00:00',351,1,372,378);
SET @max = (SELECT count(*) FROM event where patient_id=208);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,hemorrhage_cause_id,hemorrhage_treatment_id) VALUES (208,0,0,'espamacs.event.Hemorrhage',@max,'2015-06-07 00:00:00',351,0,371,378);
SET @max = (SELECT count(*) FROM event where patient_id=211);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,hemorrhage_cause_id,hemorrhage_treatment_id) VALUES (211,0,0,'espamacs.event.Hemorrhage',@max,'2014-09-08 00:00:00',351,1,372,377);
SET @max = (SELECT count(*) FROM event where patient_id=217);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,hemorrhage_cause_id,hemorrhage_treatment_id) VALUES (217,0,0,'espamacs.event.Hemorrhage',@max,'2015-05-05 00:00:00',351,1,369,376);
SET @max = (SELECT count(*) FROM event where patient_id=273);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,hemorrhage_cause_id,hemorrhage_treatment_id) VALUES (273,0,0,'espamacs.event.Hemorrhage',@max,'2014-07-09 00:00:00',351,1,371,377);
SET @max = (SELECT count(*) FROM event where patient_id=282);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,hemorrhage_cause_id,hemorrhage_treatment_id) VALUES (282,0,0,'espamacs.event.Hemorrhage',@max,'2016-01-14 00:00:00',351,0,369,376);
SET @max = (SELECT count(*) FROM event where patient_id=152);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,hemorrhage_cause_id,hemorrhage_treatment_id) VALUES (152,0,0,'espamacs.event.Hemorrhage',@max,'2015-07-26 00:00:00',354,0,369,376);
SET @max = (SELECT count(*) FROM event where patient_id=335);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,hemorrhage_cause_id,hemorrhage_treatment_id) VALUES (335,0,0,'espamacs.event.Hemorrhage',@max,'2016-03-18 00:00:00',351,0,371,377);
SET @max = (SELECT count(*) FROM event where patient_id=335);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,hemorrhage_cause_id,hemorrhage_treatment_id) VALUES (335,0,0,'espamacs.event.Hemorrhage',@max,'2016-03-20 00:00:00',351,0,371,377);

-- Infecciones
SET @max = (SELECT count(*) FROM event where patient_id=24);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,infection_place_id,infection_treatment_id) VALUES (24,0,0,'espamacs.event.Infection',@max,'2014-09-16 00:00:00',351,0,392,401);
SET @max = (SELECT count(*) FROM event where patient_id=77);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,infection_place_id,infection_treatment_id) VALUES (77,0,0,'espamacs.event.Infection',@max,'2014-12-23 00:00:00',354,0,399,401);
SET @max = (SELECT count(*) FROM event where patient_id=84);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,infection_place_id,infection_treatment_id) VALUES (84,0,0,'espamacs.event.Infection',@max,'2013-02-14 00:00:00',352,0,392,401);
SET @max = (SELECT count(*) FROM event where patient_id=151);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,infection_place_id,infection_treatment_id) VALUES (151,0,0,'espamacs.event.Infection',@max,'2015-04-07 00:00:00',354,0,392,401);
SET @max = (SELECT count(*) FROM event where patient_id=308);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,infection_place_id,infection_treatment_id) VALUES (308,0,0,'espamacs.event.Infection',@max,'2015-12-15 00:00:00',351,0,391,401);


-- Disfuncion neurologica
SET @max = (SELECT count(*) FROM event where patient_id=30);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,neurological_dysfunction_type_id,neurological_dysfunction_effect_id,neurological_dysfunction_cause_id,inr_id,aptt_id,neurological_dysfunction_place_id,neurological_dysfunction_diagnosis_id,surgery,treatement_id) VALUES (30,0,0,'espamacs.event.NeurologicalDysfunction',@max,'2014-10-14 00:00:00',351,0,404,411,417,419,422,429,430,0,435);
SET @max = (SELECT count(*) FROM event where patient_id=35);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,neurological_dysfunction_type_id,neurological_dysfunction_effect_id,neurological_dysfunction_cause_id,inr_id,aptt_id,neurological_dysfunction_place_id,neurological_dysfunction_diagnosis_id,surgery,treatement_id) VALUES (35,0,0,'espamacs.event.NeurologicalDysfunction',@max,'2014-05-05 00:00:00',351,0,407,411,417,419,422,429,430,0,435);
SET @max = (SELECT count(*) FROM event where patient_id=27);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,neurological_dysfunction_type_id,neurological_dysfunction_effect_id,neurological_dysfunction_cause_id,inr_id,aptt_id,neurological_dysfunction_place_id,neurological_dysfunction_diagnosis_id,surgery,treatement_id) VALUES (27,0,0,'espamacs.event.NeurologicalDysfunction',@max,'2014-11-02 00:00:00',351,0,404,409,415,419,422,426,430,0,435);
SET @max = (SELECT count(*) FROM event where patient_id=20);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,neurological_dysfunction_type_id,neurological_dysfunction_effect_id,neurological_dysfunction_cause_id,inr_id,aptt_id,neurological_dysfunction_place_id,neurological_dysfunction_diagnosis_id,surgery,treatement_id) VALUES (20,0,0,'espamacs.event.NeurologicalDysfunction',@max,'2014-09-01 00:00:00',354,0,404,409,415,420,423,428,430,0,435);
SET @max = (SELECT count(*) FROM event where patient_id=20);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,neurological_dysfunction_type_id,neurological_dysfunction_effect_id,neurological_dysfunction_cause_id,inr_id,aptt_id,neurological_dysfunction_place_id,neurological_dysfunction_diagnosis_id,surgery,treatement_id) VALUES (20,0,0,'espamacs.event.NeurologicalDysfunction',@max,'2014-05-28 00:00:00',354,0,404,408,415,421,424,427,430,0,435);
SET @max = (SELECT count(*) FROM event where patient_id=78);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,neurological_dysfunction_type_id,neurological_dysfunction_effect_id,neurological_dysfunction_cause_id,inr_id,aptt_id,neurological_dysfunction_place_id,neurological_dysfunction_diagnosis_id,surgery,treatement_id) VALUES (78,0,0,'espamacs.event.NeurologicalDysfunction',@max,'2015-03-23 00:00:00',354,0,405,412,415,420,423,427,430,0,439);
SET @max = (SELECT count(*) FROM event where patient_id=123);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,neurological_dysfunction_type_id,neurological_dysfunction_effect_id,neurological_dysfunction_cause_id,inr_id,aptt_id,neurological_dysfunction_place_id,neurological_dysfunction_diagnosis_id,surgery,treatement_id) VALUES (123,0,0,'espamacs.event.NeurologicalDysfunction',@max,'2014-06-19 00:00:00',352,0,404,408,415,421,424,426,430,0,436);
SET @max = (SELECT count(*) FROM event where patient_id=123);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,neurological_dysfunction_type_id,neurological_dysfunction_effect_id,neurological_dysfunction_cause_id,inr_id,aptt_id,neurological_dysfunction_place_id,neurological_dysfunction_diagnosis_id,surgery,treatement_id) VALUES (123,0,0,'espamacs.event.NeurologicalDysfunction',@max,'2014-06-23 00:00:00',352,0,404,410,415,419,422,427,430,1,436);
SET @max = (SELECT count(*) FROM event where patient_id=124);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,neurological_dysfunction_type_id,neurological_dysfunction_effect_id,neurological_dysfunction_cause_id,inr_id,aptt_id,neurological_dysfunction_place_id,neurological_dysfunction_diagnosis_id,surgery,treatement_id) VALUES (124,0,0,'espamacs.event.NeurologicalDysfunction',@max,'2014-07-27 00:00:00',351,0,406,414,415,419,422,425,430,0,435);
SET @max = (SELECT count(*) FROM event where patient_id=126);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,neurological_dysfunction_type_id,neurological_dysfunction_effect_id,neurological_dysfunction_cause_id,inr_id,aptt_id,neurological_dysfunction_place_id,neurological_dysfunction_diagnosis_id,surgery,treatement_id) VALUES (126,0,0,'espamacs.event.NeurologicalDysfunction',@max,'2014-07-30 00:00:00',351,0,404,410,415,419,422,425,430,0,436);
SET @max = (SELECT count(*) FROM event where patient_id=188);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,neurological_dysfunction_type_id,neurological_dysfunction_effect_id,neurological_dysfunction_cause_id,inr_id,aptt_id,neurological_dysfunction_place_id,neurological_dysfunction_diagnosis_id,surgery,treatement_id) VALUES (188,0,0,'espamacs.event.NeurologicalDysfunction',@max,'2015-06-11 00:00:00',351,1,404,411,415,419,422,426,430,0,435);
SET @max = (SELECT count(*) FROM event where patient_id=151);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,neurological_dysfunction_type_id,neurological_dysfunction_effect_id,neurological_dysfunction_cause_id,inr_id,aptt_id,neurological_dysfunction_place_id,neurological_dysfunction_diagnosis_id,surgery,treatement_id) VALUES (151,0,0,'espamacs.event.NeurologicalDysfunction',@max,'2015-06-24 00:00:00',354,0,404,409,418,420,423,425,433,0,436);
SET @max = (SELECT count(*) FROM event where patient_id=235);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,neurological_dysfunction_type_id,neurological_dysfunction_effect_id,neurological_dysfunction_cause_id,inr_id,aptt_id,neurological_dysfunction_place_id,neurological_dysfunction_diagnosis_id,surgery,treatement_id) VALUES (235,0,0,'espamacs.event.NeurologicalDysfunction',@max,'2015-03-14 00:00:00',351,1,405,414,417,419,422,425,430,0,435);
SET @max = (SELECT count(*) FROM event where patient_id=243);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,neurological_dysfunction_type_id,neurological_dysfunction_effect_id,neurological_dysfunction_cause_id,inr_id,aptt_id,neurological_dysfunction_place_id,neurological_dysfunction_diagnosis_id,surgery,treatement_id) VALUES (243,0,0,'espamacs.event.NeurologicalDysfunction',@max,'2014-04-20 00:00:00',351,1,405,414,415,421,424,427,430,1,435);
SET @max = (SELECT count(*) FROM event where patient_id=204);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,neurological_dysfunction_type_id,neurological_dysfunction_effect_id,neurological_dysfunction_cause_id,inr_id,aptt_id,neurological_dysfunction_place_id,neurological_dysfunction_diagnosis_id,surgery,treatement_id) VALUES (204,0,0,'espamacs.event.NeurologicalDysfunction',@max,'2015-03-22 00:00:00',351,0,404,408,415,421,424,426,430,0,435);
SET @max = (SELECT count(*) FROM event where patient_id=257);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,neurological_dysfunction_type_id,neurological_dysfunction_effect_id,neurological_dysfunction_cause_id,inr_id,aptt_id,neurological_dysfunction_place_id,neurological_dysfunction_diagnosis_id,surgery,treatement_id) VALUES (257,0,0,'espamacs.event.NeurologicalDysfunction',@max,'2015-10-29 00:00:00',351,0,404,411,417,419,422,426,430,0,438);
SET @max = (SELECT count(*) FROM event where patient_id=271);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,neurological_dysfunction_type_id,neurological_dysfunction_effect_id,neurological_dysfunction_cause_id,inr_id,aptt_id,neurological_dysfunction_place_id,neurological_dysfunction_diagnosis_id,surgery,treatement_id) VALUES (271,0,0,'espamacs.event.NeurologicalDysfunction',@max,'2015-11-27 00:00:00',351,1,404,411,418,419,422,425,430,0,437);
SET @max = (SELECT count(*) FROM event where patient_id=271);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,neurological_dysfunction_type_id,neurological_dysfunction_effect_id,neurological_dysfunction_cause_id,inr_id,aptt_id,neurological_dysfunction_place_id,neurological_dysfunction_diagnosis_id,surgery,treatement_id) VALUES (271,0,0,'espamacs.event.NeurologicalDysfunction',@max,'2015-12-01 00:00:00',351,0,404,411,418,419,422,425,430,0,437);
SET @max = (SELECT count(*) FROM event where patient_id=289);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,neurological_dysfunction_type_id,neurological_dysfunction_effect_id,neurological_dysfunction_cause_id,inr_id,aptt_id,neurological_dysfunction_place_id,neurological_dysfunction_diagnosis_id,surgery,treatement_id) VALUES (289,0,0,'espamacs.event.NeurologicalDysfunction',@max,'2015-10-03 00:00:00',351,0,404,410,415,420,423,429,430,0,436);

-- ARRITMIA
SET @max = (SELECT count(*) FROM event where patient_id=36);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,arrhythmia_type_id) VALUES (36,0,0,'espamacs.event.Arrhythmia',@max,'2014-05-21 00:00:00',351,1,440);
SET @max = (SELECT count(*) FROM event where patient_id=38);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,arrhythmia_type_id) VALUES (38,0,0,'espamacs.event.Arrhythmia',@max,'2014-04-16 00:00:00',352,1,440);
SET @max = (SELECT count(*) FROM event where patient_id=76);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,arrhythmia_type_id) VALUES (76,0,0,'espamacs.event.Arrhythmia',@max,'2015-01-17 00:00:00',354,0,440);
SET @max = (SELECT count(*) FROM event where patient_id=76);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,arrhythmia_type_id) VALUES (76,0,0,'espamacs.event.Arrhythmia',@max,'2015-01-12 00:00:00',354,0,440);
SET @max = (SELECT count(*) FROM event where patient_id=84);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,arrhythmia_type_id) VALUES (84,0,0,'espamacs.event.Arrhythmia',@max,'2013-02-11 00:00:00',352,0,440);
SET @max = (SELECT count(*) FROM event where patient_id=87);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,arrhythmia_type_id) VALUES (87,0,0,'espamacs.event.Arrhythmia',@max,'2013-02-09 00:00:00',351,0,440);
SET @max = (SELECT count(*) FROM event where patient_id=87);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,arrhythmia_type_id) VALUES (87,0,0,'espamacs.event.Arrhythmia',@max,'2013-02-10 00:00:00',351,0,440);
SET @max = (SELECT count(*) FROM event where patient_id=272);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,arrhythmia_type_id) VALUES (272,0,0,'espamacs.event.Arrhythmia',@max,'2015-12-14 00:00:00',351,0,440);
SET @max = (SELECT count(*) FROM event where patient_id=300);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,arrhythmia_type_id) VALUES (300,0,0,'espamacs.event.Arrhythmia',@max,'2014-03-07 00:00:00',351,0,441);
SET @max = (SELECT count(*) FROM event where patient_id=308);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,arrhythmia_type_id) VALUES (308,0,0,'espamacs.event.Arrhythmia',@max,'2015-12-25 00:00:00',351,1,440);

-- Disfuncion renal
SET @max = (SELECT count(*) FROM event where patient_id=24);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,creatinine,therapy_days,recover_renal_functionality,renal_dysfunction_treatment_id) VALUES (24,0,0,'espamacs.event.RenalDysfunction',@max,'2014-11-12 00:00:00',351,0,4,23,0,443);
SET @max = (SELECT count(*) FROM event where patient_id=73);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,creatinine,therapy_days,recover_renal_functionality,renal_dysfunction_treatment_id) VALUES (73,0,0,'espamacs.event.RenalDysfunction',@max,'2015-01-09 00:00:00',351,0,3.98,2,0,442);
SET @max = (SELECT count(*) FROM event where patient_id=282);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,creatinine,therapy_days,recover_renal_functionality,renal_dysfunction_treatment_id) VALUES (282,0,0,'espamacs.event.RenalDysfunction',@max,'2016-01-13 00:00:00',351,0,1.29,5,0,443);

-- Fallo respiratorio
SET @max = (SELECT count(*) FROM event where patient_id=39);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,days_with_respiratory_problems,tracheotomy) VALUES (39,0,0,'espamacs.event.RespiratoryFailure',@max,'2014-04-02 00:00:00',351,1,0,0);
SET @max = (SELECT count(*) FROM event where patient_id=40);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,days_with_respiratory_problems,tracheotomy) VALUES (40,0,0,'espamacs.event.RespiratoryFailure',@max,'2014-12-11 00:00:00',351,0,1,0);
SET @max = (SELECT count(*) FROM event where patient_id=131);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,days_with_respiratory_problems,tracheotomy) VALUES (131,0,0,'espamacs.event.RespiratoryFailure',@max,'2015-04-28 00:00:00',351,0,1,0);
SET @max = (SELECT count(*) FROM event where patient_id=182);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,days_with_respiratory_problems,tracheotomy) VALUES (182,0,0,'espamacs.event.RespiratoryFailure',@max,'2015-04-25 00:00:00',351,0,2,0);
SET @max = (SELECT count(*) FROM event where patient_id=250);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,days_with_respiratory_problems,tracheotomy) VALUES (250,0,0,'espamacs.event.RespiratoryFailure',@max,'2014-02-11 00:00:00',351,1,9,0);
SET @max = (SELECT count(*) FROM event where patient_id=256);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,days_with_respiratory_problems,tracheotomy) VALUES (256,0,0,'espamacs.event.RespiratoryFailure',@max,'2015-10-12 00:00:00',351,0,6,0);

-- Derrame pericardico
SET @max = (SELECT count(*) FROM event where patient_id=107);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,pericardial_effussion_quantity_id,pericardial_effussion_drain_method_id,flow_blocking) VALUES (107,0,0,'espamacs.event.PericardialEffusion',@max,'2014-02-17 00:00:00',351,1,472,474,1);
SET @max = (SELECT count(*) FROM event where patient_id=185);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,pericardial_effussion_quantity_id,pericardial_effussion_drain_method_id,flow_blocking) VALUES (185,0,0,'espamacs.event.PericardialEffusion',@max,'2014-01-22 00:00:00',351,1,472,474,1);
SET @max = (SELECT count(*) FROM event where patient_id=214);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,pericardial_effussion_quantity_id,pericardial_effussion_drain_method_id,flow_blocking) VALUES (214,0,0,'espamacs.event.PericardialEffusion',@max,'2014-01-29 00:00:00',351,1,472,475,1);
SET @max = (SELECT count(*) FROM event where patient_id=302);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,pericardial_effussion_quantity_id,pericardial_effussion_drain_method_id,flow_blocking) VALUES (302,0,0,'espamacs.event.PericardialEffusion',@max,'2015-12-27 00:00:00',352,1,472,475,1);


-- IC Dercha
SET @max = (SELECT count(*) FROM event where patient_id=159);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (159,0,0,'espamacs.event.RightHeartFailure',@max,'2012-03-07 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=330);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (330,0,0,'espamacs.event.RightHeartFailure',@max,'2016-03-19 00:00:00',351,1);

-- OTRO EVENTO
SET @max = (SELECT count(*) FROM event where patient_id=35);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (35,0,0,'espamacs.event.OtherEvent',@max,'2014-05-07 00:00:00',351,1,'Muerte encefálica y retirada de ECMO');
SET @max = (SELECT count(*) FROM event where patient_id=37);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (37,0,0,'espamacs.event.OtherEvent',@max,'2014-04-11 00:00:00',351,1,'ECMO posttrasplante cardiaco - Fallo primario del injerto');
SET @max = (SELECT count(*) FROM event where patient_id=60);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (60,0,0,'espamacs.event.OtherEvent',@max,'2012-09-21 00:00:00',351,1,'Fracaso multiorgánico');
SET @max = (SELECT count(*) FROM event where patient_id=85);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (85,0,0,'espamacs.event.OtherEvent',@max,'2013-12-30 00:00:00',351,0,'');
SET @max = (SELECT count(*) FROM event where patient_id=86);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (86,0,0,'espamacs.event.OtherEvent',@max,'2013-12-30 00:00:00',351,1,'');
SET @max = (SELECT count(*) FROM event where patient_id=24);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (24,0,0,'espamacs.event.OtherEvent',@max,'2014-09-28 00:00:00',351,0,'');
SET @max = (SELECT count(*) FROM event where patient_id=91);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (91,0,0,'espamacs.event.OtherEvent',@max,'2014-01-25 00:00:00',351,0,'rechazo hiperagudo del injerto (TCO)');
SET @max = (SELECT count(*) FROM event where patient_id=92);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (92,0,0,'espamacs.event.OtherEvent',@max,'2014-06-20 00:00:00',351,1,'FMO mantenido, también isquemia EI de la ECMO');
SET @max = (SELECT count(*) FROM event where patient_id=95);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (95,0,0,'espamacs.event.OtherEvent',@max,'2013-03-23 00:00:00',351,0,'');
SET @max = (SELECT count(*) FROM event where patient_id=99);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (99,0,0,'espamacs.event.OtherEvent',@max,'2014-10-04 00:00:00',351,1,'Shock septico');
SET @max = (SELECT count(*) FROM event where patient_id=100);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (100,0,0,'espamacs.event.OtherEvent',@max,'2014-10-25 00:00:00',351,1,'DISECCIÓN AORTICA RETROGRADA DESDE CANULA DE ENTRADA FEMORAL');
SET @max = (SELECT count(*) FROM event where patient_id=109);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (109,0,0,'espamacs.event.OtherEvent',@max,'2014-10-09 00:00:00',351,1,'');
SET @max = (SELECT count(*) FROM event where patient_id=110);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (110,0,0,'espamacs.event.OtherEvent',@max,'2014-08-21 00:00:00',351,1,'');
SET @max = (SELECT count(*) FROM event where patient_id=111);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (111,0,0,'espamacs.event.OtherEvent',@max,'2014-06-20 00:00:00',351,1,'');
SET @max = (SELECT count(*) FROM event where patient_id=114);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (114,0,0,'espamacs.event.OtherEvent',@max,'2014-05-31 00:00:00',351,1,'');
SET @max = (SELECT count(*) FROM event where patient_id=117);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (117,0,0,'espamacs.event.OtherEvent',@max,'2014-02-28 00:00:00',351,1,'');
SET @max = (SELECT count(*) FROM event where patient_id=118);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (118,0,0,'espamacs.event.OtherEvent',@max,'2014-03-02 00:00:00',351,1,'');
SET @max = (SELECT count(*) FROM event where patient_id=119);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (119,0,0,'espamacs.event.OtherEvent',@max,'2013-06-20 00:00:00',351,1,'');
SET @max = (SELECT count(*) FROM event where patient_id=120);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (120,0,0,'espamacs.event.OtherEvent',@max,'2013-07-30 00:00:00',351,1,'');
SET @max = (SELECT count(*) FROM event where patient_id=121);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (121,0,0,'espamacs.event.OtherEvent',@max,'2015-02-02 00:00:00',352,0,'Infección de driveline y urinaria con buena respuesta a tratamiento antibiotico oral');
SET @max = (SELECT count(*) FROM event where patient_id=149);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (149,0,0,'espamacs.event.OtherEvent',@max,'2014-06-19 00:00:00',351,1,'Shock séptico por infección por S. pyogenes. FMO. SDRA. Éxitus');
SET @max = (SELECT count(*) FROM event where patient_id=187);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (187,0,0,'espamacs.event.OtherEvent',@max,'2015-05-19 00:00:00',351,0,'Daño neurológico severo por hipoxia mantenida.');
SET @max = (SELECT count(*) FROM event where patient_id=201);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (201,0,0,'espamacs.event.OtherEvent',@max,'2014-01-03 00:00:00',351,1,'shock multifactorial');
SET @max = (SELECT count(*) FROM event where patient_id=219);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (219,0,0,'espamacs.event.OtherEvent',@max,'2015-07-17 00:00:00',351,0,'Isquemia distal miembro inferior izquierdo en relación a canulación arteria femoral percutánea.');
SET @max = (SELECT count(*) FROM event where patient_id=151);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (151,0,0,'espamacs.event.OtherEvent',@max,'2015-08-21 00:00:00',351,1,'isquemia colónica diagnóstico por TC');
SET @max = (SELECT count(*) FROM event where patient_id=239);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (239,0,0,'espamacs.event.OtherEvent',@max,'2015-07-27 00:00:00',351,1,'isquemia mesentérica');
SET @max = (SELECT count(*) FROM event where patient_id=258);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (258,0,0,'espamacs.event.OtherEvent',@max,'2015-07-24 00:00:00',354,0,'Alta hospitalaria (Terapia de Destino)');
SET @max = (SELECT count(*) FROM event where patient_id=276);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (276,0,0,'espamacs.event.OtherEvent',@max,'2015-07-28 00:00:00',351,1,'Isquemia intestinal por bajo gasto');
SET @max = (SELECT count(*) FROM event where patient_id=293);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (293,0,0,'espamacs.event.OtherEvent',@max,'2015-11-10 00:00:00',351,0,'Disfunción ventricular izquierda. Infección sin hemocultivos positivos');
SET @max = (SELECT count(*) FROM event where patient_id=152);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (152,0,0,'espamacs.event.OtherEvent',@max,'2015-03-04 00:00:00',354,0,'Derrame pleural izquierdo seroso');
SET @max = (SELECT count(*) FROM event where patient_id=308);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (308,0,0,'espamacs.event.OtherEvent',@max,'2015-12-15 00:00:00',351,0,'Isquemia pierna derecha. Reperfusión arteria pedia');
SET @max = (SELECT count(*) FROM event where patient_id=199);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (199,0,0,'espamacs.event.OtherEvent',@max,'2015-07-03 00:00:00',351,0,'Colecistectomía laparoscópica por colecistitis y pancreatitis');
SET @max = (SELECT count(*) FROM event where patient_id=129);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (129,0,0,'espamacs.event.OtherEvent',@max,'2016-02-02 00:00:00',351,1,'Exitus letalis');
SET @max = (SELECT count(*) FROM event where patient_id=150);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death,text) VALUES (150,0,0,'espamacs.event.OtherEvent',@max,'2016-01-20 00:00:00',354,0,'Infección herida quirúrgica "driveline"');

-- RETIRADAS DE ASISTENCIA
-- Por recuperacion
SET @max = (SELECT count(*) FROM event where patient_id=31);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (31,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-09-16 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=29);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (29,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-10-28 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=36);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (36,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-05-16 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=38);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (38,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-04-09 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=41);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (41,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-04-09 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=48);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (48,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-03-03 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=49);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (49,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-03-10 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=43);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (43,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-05-20 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=58);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (58,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2011-01-14 00:00:00',353,0);
SET @max = (SELECT count(*) FROM event where patient_id=62);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (62,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-02-17 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=64);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (64,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-01-21 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=65);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (65,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-01-05 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=23);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (23,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-10-15 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=19);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (19,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-10-05 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=25);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (25,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-08-30 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=44);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (44,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-02-11 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=45);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (45,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-05-27 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=82);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (82,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-01-06 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=83);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (83,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-06-07 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=75);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (75,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-01-30 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=93);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (93,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-06-23 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=94);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (94,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-07-13 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=96);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (96,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2013-03-15 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=97);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (97,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2013-04-29 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=102);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (102,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-12-01 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=103);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (103,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-02-13 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=116);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (116,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-05-26 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=46);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (46,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-12-11 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=106);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (106,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-03-04 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=40);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (40,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-01-03 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=105);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (105,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-03-09 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=192);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (192,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-03-26 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=194);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (194,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-06-18 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=198);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (198,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-04-07 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=200);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (200,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-04-13 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=203);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (203,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-03-13 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=206);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (206,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-02-11 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=209);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (209,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-07-24 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=210);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (210,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-06-24 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=212);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (212,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-10-30 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=218);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (218,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-06-05 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=175);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (175,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-05-20 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=189);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (189,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-06-17 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=219);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (219,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-07-20 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=156);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (156,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-05-25 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=231);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (231,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2013-11-21 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=232);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (232,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-01-22 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=202);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (202,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-07-08 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=236);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (236,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-12-01 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=237);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (237,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-07-29 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=238);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (238,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-05-09 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=241);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (241,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-07-13 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=242);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (242,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-06-01 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=245);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (245,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-08-10 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=249);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (249,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-06-16 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=246);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (246,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-09-02 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=251);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (251,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-09-19 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=261);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (261,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-11-04 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=254);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (254,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-10-05 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=274);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (274,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2014-01-08 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=255);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (255,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-09-28 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=269);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (269,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-12-01 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=279);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (279,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-06-15 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=280);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (280,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-07-07 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=270);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (270,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2016-01-20 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=278);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (278,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2016-01-13 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=282);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (282,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2016-01-16 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=287);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (287,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-08-05 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=290);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (290,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-10-11 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=291);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (291,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-10-29 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=292);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (292,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-11-05 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=295);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (295,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-11-06 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=298);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (298,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-12-21 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=88);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (88,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-01-22 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=324);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (324,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2015-12-29 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=277);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (277,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2016-01-08 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=281);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (281,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2016-02-02 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=283);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (283,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2016-01-15 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=334);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (334,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2016-02-22 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=331);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (331,0,0,'espamacs.event.RemovedAssistanceHealed',@max,'2016-03-30 00:00:00',351,0);

-- Por transplante

SET @max = (SELECT count(*) FROM event where patient_id=32);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (32,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2014-08-07 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=27);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (27,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2014-10-30 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=61);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (61,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2014-03-03 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=21);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (21,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2015-02-06 00:00:00',352,0);
SET @max = (SELECT count(*) FROM event where patient_id=20);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (20,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2014-11-25 00:00:00',354,0);
SET @max = (SELECT count(*) FROM event where patient_id=18);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (18,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2014-07-21 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=80);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (80,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2015-01-27 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=84);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (84,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2013-06-07 00:00:00',354,0);
SET @max = (SELECT count(*) FROM event where patient_id=87);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (87,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2013-05-30 00:00:00',354,0);
SET @max = (SELECT count(*) FROM event where patient_id=90);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (90,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2014-01-01 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=101);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (101,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2014-11-11 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=76);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (76,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2015-02-28 00:00:00',354,1);
SET @max = (SELECT count(*) FROM event where patient_id=122);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (122,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2014-03-15 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=57);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (57,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2011-01-14 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=125);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (125,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2014-08-17 00:00:00',354,0);
SET @max = (SELECT count(*) FROM event where patient_id=128);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (128,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2014-08-14 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=148);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (148,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2014-04-10 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=72);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (72,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2015-01-11 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=174);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (174,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2015-05-08 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=181);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (181,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2013-09-26 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=112);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (112,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2015-03-25 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=47);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (47,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2014-12-18 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=115);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (115,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2015-05-07 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=195);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (195,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2015-07-27 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=204);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (204,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2015-06-10 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=247);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (247,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2015-09-30 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=248);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (248,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2015-08-29 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=286);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (286,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2015-07-14 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=288);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (288,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2015-09-18 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=294);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (294,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2015-11-25 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=296);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (296,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2015-11-18 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=297);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (297,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2015-12-20 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=77);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (77,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2015-04-20 00:00:00',354,0);
SET @max = (SELECT count(*) FROM event where patient_id=108);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (108,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2015-05-12 00:00:00',354,0);
SET @max = (SELECT count(*) FROM event where patient_id=197);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (197,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2015-10-18 00:00:00',354,0);
SET @max = (SELECT count(*) FROM event where patient_id=199);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (199,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2015-08-28 00:00:00',354,0);
SET @max = (SELECT count(*) FROM event where patient_id=150);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (150,0,0,'espamacs.event.RemovedAssistanceTransplant',@max,'2016-01-24 00:00:00',352,0);

-- Por cambio
SET @max = (SELECT count(*) FROM event where patient_id=28);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (28,0,0,'espamacs.event.RemovedAssistanceChanged',@max,'2014-10-11 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=50);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (50,0,0,'espamacs.event.RemovedAssistanceChanged',@max,'2015-01-14 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=79);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (79,0,0,'espamacs.event.RemovedAssistanceChanged',@max,'2015-01-23 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=26);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (26,0,0,'espamacs.event.RemovedAssistanceChanged',@max,'2013-02-07 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=89);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (89,0,0,'espamacs.event.RemovedAssistanceChanged',@max,'2013-12-18 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=113);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (113,0,0,'espamacs.event.RemovedAssistanceChanged',@max,'2014-05-30 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=123);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (123,0,0,'espamacs.event.RemovedAssistanceChanged',@max,'2014-06-23 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=126);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (126,0,0,'espamacs.event.RemovedAssistanceChanged',@max,'2014-08-06 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=193);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (193,0,0,'espamacs.event.RemovedAssistanceChanged',@max,'2015-04-10 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=208);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (208,0,0,'espamacs.event.RemovedAssistanceChanged',@max,'2014-06-12 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=216);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (216,0,0,'espamacs.event.RemovedAssistanceChanged',@max,'2015-04-17 00:00:00',351,1);
SET @max = (SELECT count(*) FROM event where patient_id=234);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (234,0,0,'espamacs.event.RemovedAssistanceChanged',@max,'2014-12-22 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=244);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (244,0,0,'espamacs.event.RemovedAssistanceChanged',@max,'2015-07-26 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=259);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (259,0,0,'espamacs.event.RemovedAssistanceChanged',@max,'2015-11-20 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=78);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (78,0,0,'espamacs.event.RemovedAssistanceChanged',@max,'2015-04-15 00:00:00',351,0);
SET @max = (SELECT count(*) FROM event where patient_id=329);INSERT INTO event (patient_id,version,remove_assistance,class,events_idx,event_date,patient_health_status_id,patient_death) VALUES (329,0,0,'espamacs.event.RemovedAssistanceChanged',@max,'2016-03-11 00:00:00',351,0);


update patient p, event e, initial_data id set id.exitus_data_exitus_date=e.event_date where  p.initial_data_id = id.id and p.id < 1000 and e.patient_id=p.id and e.patient_death=1;

unlock tables;
COMMIT;